name: flutter_application_1
description: A new Flutter project.

publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.0
  http: ^1.2.2
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  sqflite_common_ffi: ^2.3.0  # Si vous utilisez FFI pour SQLite

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
